imports:
    - { resource: '@EnhavoArticleBundle/Resources/config/app/search.yml' }
    - { resource: '@EnhavoPageBundle/Resources/config/app/search.yml' }
    - { resource: '@EnhavoShopBundle/Resources/config/app/search.yml' }
    - { resource: '@EnhavoGridBundle/Resources/config/app/search.yml' }