webpack_encore:
    output_path: '%kernel.project_dir%/public/build/enhavo'
    builds:
        enhavo: '%kernel.project_dir%/public/build/enhavo'
        theme: '%kernel.project_dir%/public/build/theme'
