imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @EnhavoShopBundle/Resources/config/config.yml }
    - { resource: @EnhavoAssetsBundle/Resources/config/config.yml }
    - { resource: enhavo.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        enable_annotations: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime: 25920000
        handler_id: session.handler.pdo
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'EnhavoAppBundle:Form:fields.html.twig'
            - 'EnhavoGridBundle:Form:fields.html.twig'
            - 'EnhavoCategoryBundle:Form:fields.html.twig'
            - 'EnhavoMediaBundle:Form:fields.html.twig'
            - 'EnhavoShopBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        resolve_target_entities:
            Enhavo\Bundle\CategoryBundle\Model\CategoryInterface: Enhavo\Bundle\CategoryBundle\Entity\Category
            Enhavo\Bundle\CategoryBundle\Model\CollectionInterface: Enhavo\Bundle\CategoryBundle\Entity\Collection

            Enhavo\Bundle\WorkflowBundle\Model\WorkflowStatusInterface: Enhavo\Bundle\WorkflowBundle\Entity\WorkflowStatus
            Enhavo\Bundle\WorkflowBundle\Model\NodeInterface: Enhavo\Bundle\WorkflowBundle\Entity\Node
            Enhavo\Bundle\WorkflowBundle\Model\TransitionInterface: Enhavo\Bundle\WorkflowBundle\Entity\Transition
            Enhavo\Bundle\WorkflowBundle\Model\WorkflowInterface: Enhavo\Bundle\WorkflowBundle\Entity\Workflow

            Enhavo\Bundle\DownloadBundle\Model\DownloadInterface: Enhavo\Bundle\DownloadBundle\Entity\Download

            Enhavo\Bundle\GridBundle\Model\GridInterface: Enhavo\Bundle\GridBundle\Entity\Grid
            Enhavo\Bundle\GridBundle\Model\ItemInterface: Enhavo\Bundle\GridBundle\Entity\Item
            Enhavo\Bundle\GridBundle\Model\ContainerInterface: Enhavo\Bundle\GridBundle\Entity\Container
            Enhavo\Bundle\GridBundle\Model\ColumnInterface: Enhavo\Bundle\GridBundle\Entity\Column

            Enhavo\Bundle\MediaBundle\Model\FileInterface: Enhavo\Bundle\MediaBundle\Entity\File

            Enhavo\Bundle\AppBundle\Model\RouteInterface: Enhavo\Bundle\AppBundle\Entity\Route

            Enhavo\Bundle\SliderBundle\Model\SliderInterface: Enhavo\Bundle\SliderBundle\Entity\Slider
            Enhavo\Bundle\SliderBundle\Model\SliderInterface: Enhavo\Bundle\SliderBundle\Entity\Slider

            Enhavo\Bundle\UserBundle\Model\UserInterface: Enhavo\Bundle\UserBundle\Entity\User
            Enhavo\Bundle\UserBundle\Model\GroupInterface: Enhavo\Bundle\UserBundle\Entity\Group

            Sylius\Component\Addressing\Model\AddressInterface: Sylius\Component\Addressing\Model\Address
            Sylius\Component\Promotion\Model\CouponInterface: Sylius\Component\Promotion\Model\Coupon
            Sylius\Component\Payment\Model\PaymentInterface: Sylius\Component\Payment\Model\Payment
            Sylius\Component\Shipping\Model\ShipmentInterface: Sylius\Component\Shipping\Model\Shipment
            Sylius\Component\Taxation\Model\TaxRateInterface: Sylius\Component\Taxation\Model\TaxRate
            Sylius\Component\Promotion\Model\PromotionInterface: Enhavo\Bundle\ShopBundle\Entity\Promotion

            Enhavo\Bundle\ShopBundle\Model\OrderInterface: Enhavo\Bundle\ShopBundle\Entity\Order


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host: %mailer_host%
    username: %mailer_user%
    password: %mailer_password%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Enhavo\Bundle\UserBundle\Entity\User
    group:
        group_class: Enhavo\Bundle\UserBundle\Entity\Group

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        news_thumb:
            quality: 75
            filters:
                thumbnail: { size: [300, 110], mode: outbound }

cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true
        route_provider_service_id: enhavo_app.route_provider

parameters:
    pdo.db_options:
        db_table: app_session
        db_id_col: id
        db_data_col: value
        db_time_col: time
        db_lifetime_col: lifetime
        gc_maxlifetime: 3600

services:
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%database_host%;dbname=%database_name%"
            - "%database_user%"
            - "%database_password%"
        calls:
            - [setAttribute, [3, 2]]

    session.handler.pdo:
        class:     Enhavo\Bundle\AppBundle\Session\PdoSessionHandler
        arguments: ["@pdo", "%pdo.db_options%"]


stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable: true
            timestampable: true

sylius_resource:
    translation:
        default_locale: "%locale%"
        locale_provider: enhavo.translation.locale_provider.contextual