imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: enhavo.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        enable_annotations: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime: 25920000
        handler_id: session.handler.pdo
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'EnhavoAppBundle:Form:fields.html.twig'
            - 'EnhavoGridBundle:Form:fields.html.twig'
            - 'EnhavoCategoryBundle:Form:fields.html.twig'
            - 'EnhavoMediaBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        jsminplus: ~
        cssmin: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host: %mailer_host%
    username: %mailer_user%
    password: %mailer_password%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Enhavo\Bundle\UserBundle\Entity\User
    group:
        group_class: Enhavo\Bundle\UserBundle\Entity\Group

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        news_thumb:
            quality: 75
            filters:
                thumbnail: { size: [300, 110], mode: outbound }

cmf_routing:
# Use this settings if you want to provide some dynamic routing features
#    chain:
#        routers_by_id:
#            router.default: 200
#            cmf_routing.dynamic_router: 100
#    dynamic:
#        enabled: true
#        route_provider_service_id: enhavo_app.route_provider

enhavo_newsletter:
    subscriber:
        send_from: 'test@test.com'
        subject: 'TestSubject'
        template:  'EnhavoNewsletterBundle:Default:subscriber-email.html.twig'

parameters:
    pdo.db_options:
        db_table:    app_session
        db_id_col:   id
        db_data_col: value
        db_time_col: time
        db_lifetime_col: lifetime

services:
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%database_host%;dbname=%database_name%"
            - "%database_user%"
            - "%database_password%"
        calls:
            - [setAttribute, [3, 2]]

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo.db_options%"]

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            sluggable: true # not needed: listeners are not enabled by default
