imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: true
        only_exceptions: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname: '%database_name%_test'

parameters:
     locale: en

enhavo_contact:
    forms:
        contact:
            recipient: 'admin@enhavo.com'
            from: 'no-reply@enhavo.com'
            sender_name: 'enhavo'