imports:
    - { resource: parameters.yml }
    - { resource: @EnhavoAppBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoArticleBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoAssetsBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoCalendarBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoCategoryBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoContactBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoContentBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoDashboardBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoDownloadBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoGeneratorBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoGridBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoInstallerBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoMediaBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoMigrationBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoNewsletterBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoPageBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoSearchBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoSerializerBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoSettingBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoShopBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoSliderBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoShopBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoThemeBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoTranslationBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoUserBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoWorkflowBundle/Resources/config/app/config.yml }
    - { resource: @EnhavoProjectBundle/Resources/config/app/config.yml }
    - { resource: security.yml }
    - { resource: enhavo.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#parameters:
#    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        # handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }