#
# enhavo
#
enhavo_contact:
    resource: "@EnhavoContactBundle/Resources/config/routing.yml"
    prefix:   /

enhavo_media:
    resource: "@EnhavoMediaBundle/Resources/config/routing.yml"

enhavo_user_security:
    resource: "@EnhavoUserBundle/Resources/config/routing/security.yml"

enhavo_admin:
    resource: "@EnhavoAppBundle/Resources/config/routing/admin.yml"
    prefix: /admin

enhavo_dashboard:
    resource: "@EnhavoDashboardBundle/Resources/config/routing.yml"
    prefix:   /admin

enhavo_article:
    resource: "@EnhavoArticleBundle/Resources/config/routing/article.yml"
    prefix: /admin

enhavo_page:
    resource: "@EnhavoPageBundle/Resources/config/routing/page.yml"
    prefix: /admin

enhavo_download:
    resource: "@EnhavoDownloadBundle/Resources/config/routing/download.yml"
    prefix: /admin

enhavo_slide:
    resource: "@EnhavoSliderBundle/Resources/config/routing/slide.yml"
    prefix: /admin

enhavo_user:
    resource: "@EnhavoUserBundle/Resources/config/routing/user.yml"
    prefix: /admin

enhavo_group:
    resource: "@EnhavoUserBundle/Resources/config/routing/group.yml"
    prefix: /admin

enhavo_grid:
    resource: "@EnhavoGridBundle/Resources/config/routing/routing.yml"
    prefix: /admin

enhavo_newsletter_newsletter:
    resource: "@EnhavoNewsletterBundle/Resources/config/routing/newsletter.yml"
    prefix:   /admin

enhavo_newsletter_subscriber:
    resource: "@EnhavoNewsletterBundle/Resources/config/routing/subscriber.yml"
    prefix:   /

enhavo_category_category:
    resource: "@EnhavoCategoryBundle/Resources/config/routing/category.yml"
    prefix:   /

enhavo_workflow:
    resource: "@EnhavoWorkflowBundle/Resources/config/routing/workflow.yml"
    prefix:   /admin

enhavo_calendar:
    resource: "@EnhavoCalendarBundle/Resources/config/routing/appointment.yml"
    prefix: /admin

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"