height: 220

toolbar1: "undo redo | bold italic underline strikethrough subscript superscript removeformat | link styleselect"

toolbar2: "table | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | code"

style_formats:
    - {title: 'Bold text', inline: 'b'}
    - {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}}
    - {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}}
    - {title: 'Example 1', inline: 'span', classes: 'example1'}
    - {title: 'Example 2', inline: 'span', classes: 'example2'}
    - {title: 'Table styles'}
    - {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}

formats:
    alignleft: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'text-left'}
    aligncenter: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'text-center'}
    alignright: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'text-right'}
    alignfull: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'text-justify'}
    bold: {inline: 'strong'}
    italic: {inline: 'em'}
    underline: {inline: 'u', exact: true}
    strikethrough: {inline: 'del'}
    customformat: {inline: 'span', styles: {color: '#00ff00', fontSize: '20px'}, attributes: {title: 'My custom format'}}

plugins:
    - "advlist autolink lists link image charmap print preview anchor"
    - "searchreplace visualblocks code fullscreen"
    - "insertdatetime media table contextmenu paste autoresize enhavo_translation"

content_css: ~